// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://iymefizdnhhvulttjjrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5bWVmaXpkbmhodnVsdHRqanJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxMjQzNjQsImV4cCI6MjA3NzcwMDM2NH0._q0NRBc6apbt9w3aTPIebwC5IwZiEmheLuQJwq5QskY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);